//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type PmcsSbsInspections struct {
	ID                   uuid.UUID  `sql:"primary_key" json:"id"`
	EquipmentID          string     `json:"equipment_id"`
	GuideManual          *string    `json:"guide_manual"`
	PerformedDate        time.Time  `json:"performed_date"`
	PerformedBy          *string    `json:"performed_by"`
	CreatedAt            time.Time  `json:"created_at"`
	UpdatedAt            time.Time  `json:"updated_at"`
	Notes                *string    `json:"notes"`
	SourceType           string     `json:"source_type"`
	CustomChecklistID    *uuid.UUID `json:"custom_checklist_id"`
	CustomRevisionID     *uuid.UUID `json:"custom_revision_id"`
	CustomRevisionNumber *int32     `json:"custom_revision_number"`
	CustomChecklistName  *string    `json:"custom_checklist_name"`
}
