//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type PmcsSbsFaults struct {
	PmcsID           uuid.UUID `sql:"primary_key" json:"pmcs_id"`
	SectionID        string    `sql:"primary_key" json:"section_id"`
	ItemIndex        int32     `sql:"primary_key" json:"item_index"`
	ItemNo           string    `json:"item_no"`
	Status           string    `json:"status"`
	FaultText        string    `json:"fault_text"`
	CorrectiveAction string    `json:"corrective_action"`
	CreatedAt        time.Time `json:"created_at"`
	UpdatedAt        time.Time `json:"updated_at"`
	SectionTitle     *string   `json:"section_title"`
}
