//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
)

type UserPmcsNotices struct {
	ID         uuid.UUID `sql:"primary_key" json:"id"`
	ItemID     uuid.UUID `json:"item_id"`
	Position   int32     `json:"position"`
	Type       *string   `json:"type"`
	NoticeText string    `json:"notice_text"`
}
