//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
)

type UserPmcsItems struct {
	ID                        uuid.UUID `sql:"primary_key" json:"id"`
	SectionID                 uuid.UUID `json:"section_id"`
	Position                  int32     `json:"position"`
	Interval                  string    `json:"interval"`
	ItemToBeCheckedOrServiced string    `json:"item_to_be_checked_or_serviced"`
	PerformedBy               string    `json:"performed_by"`
}
