//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
)

type UserPmcsSections struct {
	ID         uuid.UUID `sql:"primary_key" json:"id"`
	RevisionID uuid.UUID `json:"revision_id"`
	Position   int32     `json:"position"`
	Title      string    `json:"title"`
}
