//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type UserPmcsCommunityReleases struct {
	RevisionID  uuid.UUID `sql:"primary_key" json:"revision_id"`
	ChecklistID uuid.UUID `json:"checklist_id"`
	ReleasedAt  time.Time `json:"released_at"`
}
