//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type UserPmcsCommunitySources struct {
	ChecklistID                 uuid.UUID  `sql:"primary_key" json:"checklist_id"`
	Status                      string     `json:"status"`
	CurrentReleaseRevisionID    *uuid.UUID `json:"current_release_revision_id"`
	LatestReleaseRevisionNumber int32      `json:"latest_release_revision_number"`
	FirstReleasedAt             time.Time  `json:"first_released_at"`
	UpdatedAt                   time.Time  `json:"updated_at"`
	RetiredAt                   *time.Time `json:"retired_at"`
}
