//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type UserPmcsCommunityVotes struct {
	ChecklistID uuid.UUID `sql:"primary_key" json:"checklist_id"`
	VoterUID    string    `sql:"primary_key" json:"voter_uid"`
	Direction   int16     `json:"direction"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}
