//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type UserPmcsSubscriptions struct {
	SubscriberUID        string     `sql:"primary_key" json:"subscriber_uid"`
	ChecklistID          uuid.UUID  `sql:"primary_key" json:"checklist_id"`
	InstalledRevisionID  *uuid.UUID `json:"installed_revision_id"`
	SyncVersion          int64      `json:"sync_version"`
	AccountChangeVersion int64      `json:"account_change_version"`
	CreatedAt            time.Time  `json:"created_at"`
	UpdatedAt            time.Time  `json:"updated_at"`
	DeletedAt            *time.Time `json:"deleted_at"`
}
