//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type UserPmcsRevisions struct {
	ID             uuid.UUID  `sql:"primary_key" json:"id"`
	ChecklistID    uuid.UUID  `json:"checklist_id"`
	State          string     `json:"state"`
	RevisionNumber *int32     `json:"revision_number"`
	Name           string     `json:"name"`
	Description    string     `json:"description"`
	ContentHash    []byte     `json:"content_hash"`
	CreatedAt      time.Time  `json:"created_at"`
	UpdatedAt      time.Time  `json:"updated_at"`
	PublishedAt    *time.Time `json:"published_at"`
}
