//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
)

type UserPmcsRevisionModels struct {
	RevisionID     uuid.UUID `sql:"primary_key" json:"revision_id"`
	DisplayText    string    `json:"display_text"`
	NormalizedText string    `sql:"primary_key" json:"normalized_text"`
}
