//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
)

type UserPmcsProcedureSteps struct {
	ID           uuid.UUID `sql:"primary_key" json:"id"`
	ItemID       uuid.UUID `json:"item_id"`
	Position     int32     `json:"position"`
	StepText     string    `json:"step_text"`
	FaultFoundIf string    `json:"fault_found_if"`
}
