//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var PmcsSbsInspections = newPmcsSbsInspectionsTable("public", "pmcs_sbs_inspections", "")

type pmcsSbsInspectionsTable struct {
	postgres.Table

	// Columns
	ID                   postgres.ColumnString
	EquipmentID          postgres.ColumnString
	GuideManual          postgres.ColumnString
	PerformedDate        postgres.ColumnTimestampz
	PerformedBy          postgres.ColumnString
	CreatedAt            postgres.ColumnTimestampz
	UpdatedAt            postgres.ColumnTimestampz
	Notes                postgres.ColumnString
	SourceType           postgres.ColumnString
	CustomChecklistID    postgres.ColumnString
	CustomRevisionID     postgres.ColumnString
	CustomRevisionNumber postgres.ColumnInteger
	CustomChecklistName  postgres.ColumnString

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type PmcsSbsInspectionsTable struct {
	pmcsSbsInspectionsTable

	EXCLUDED pmcsSbsInspectionsTable
}

// AS creates new PmcsSbsInspectionsTable with assigned alias
func (a PmcsSbsInspectionsTable) AS(alias string) *PmcsSbsInspectionsTable {
	return newPmcsSbsInspectionsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new PmcsSbsInspectionsTable with assigned schema name
func (a PmcsSbsInspectionsTable) FromSchema(schemaName string) *PmcsSbsInspectionsTable {
	return newPmcsSbsInspectionsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new PmcsSbsInspectionsTable with assigned table prefix
func (a PmcsSbsInspectionsTable) WithPrefix(prefix string) *PmcsSbsInspectionsTable {
	return newPmcsSbsInspectionsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new PmcsSbsInspectionsTable with assigned table suffix
func (a PmcsSbsInspectionsTable) WithSuffix(suffix string) *PmcsSbsInspectionsTable {
	return newPmcsSbsInspectionsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newPmcsSbsInspectionsTable(schemaName, tableName, alias string) *PmcsSbsInspectionsTable {
	return &PmcsSbsInspectionsTable{
		pmcsSbsInspectionsTable: newPmcsSbsInspectionsTableImpl(schemaName, tableName, alias),
		EXCLUDED:                newPmcsSbsInspectionsTableImpl("", "excluded", ""),
	}
}

func newPmcsSbsInspectionsTableImpl(schemaName, tableName, alias string) pmcsSbsInspectionsTable {
	var (
		IDColumn                   = postgres.StringColumn("id")
		EquipmentIDColumn          = postgres.StringColumn("equipment_id")
		GuideManualColumn          = postgres.StringColumn("guide_manual")
		PerformedDateColumn        = postgres.TimestampzColumn("performed_date")
		PerformedByColumn          = postgres.StringColumn("performed_by")
		CreatedAtColumn            = postgres.TimestampzColumn("created_at")
		UpdatedAtColumn            = postgres.TimestampzColumn("updated_at")
		NotesColumn                = postgres.StringColumn("notes")
		SourceTypeColumn           = postgres.StringColumn("source_type")
		CustomChecklistIDColumn    = postgres.StringColumn("custom_checklist_id")
		CustomRevisionIDColumn     = postgres.StringColumn("custom_revision_id")
		CustomRevisionNumberColumn = postgres.IntegerColumn("custom_revision_number")
		CustomChecklistNameColumn  = postgres.StringColumn("custom_checklist_name")
		allColumns                 = postgres.ColumnList{IDColumn, EquipmentIDColumn, GuideManualColumn, PerformedDateColumn, PerformedByColumn, CreatedAtColumn, UpdatedAtColumn, NotesColumn, SourceTypeColumn, CustomChecklistIDColumn, CustomRevisionIDColumn, CustomRevisionNumberColumn, CustomChecklistNameColumn}
		mutableColumns             = postgres.ColumnList{EquipmentIDColumn, GuideManualColumn, PerformedDateColumn, PerformedByColumn, CreatedAtColumn, UpdatedAtColumn, NotesColumn, SourceTypeColumn, CustomChecklistIDColumn, CustomRevisionIDColumn, CustomRevisionNumberColumn, CustomChecklistNameColumn}
		defaultColumns             = postgres.ColumnList{CreatedAtColumn, UpdatedAtColumn}
	)

	return pmcsSbsInspectionsTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:                   IDColumn,
		EquipmentID:          EquipmentIDColumn,
		GuideManual:          GuideManualColumn,
		PerformedDate:        PerformedDateColumn,
		PerformedBy:          PerformedByColumn,
		CreatedAt:            CreatedAtColumn,
		UpdatedAt:            UpdatedAtColumn,
		Notes:                NotesColumn,
		SourceType:           SourceTypeColumn,
		CustomChecklistID:    CustomChecklistIDColumn,
		CustomRevisionID:     CustomRevisionIDColumn,
		CustomRevisionNumber: CustomRevisionNumberColumn,
		CustomChecklistName:  CustomChecklistNameColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
