//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var PmcsSbsFaults = newPmcsSbsFaultsTable("public", "pmcs_sbs_faults", "")

type pmcsSbsFaultsTable struct {
	postgres.Table

	// Columns
	PmcsID           postgres.ColumnString
	SectionID        postgres.ColumnString
	ItemIndex        postgres.ColumnInteger
	ItemNo           postgres.ColumnString
	Status           postgres.ColumnString
	FaultText        postgres.ColumnString
	CorrectiveAction postgres.ColumnString
	CreatedAt        postgres.ColumnTimestampz
	UpdatedAt        postgres.ColumnTimestampz
	SectionTitle     postgres.ColumnString

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type PmcsSbsFaultsTable struct {
	pmcsSbsFaultsTable

	EXCLUDED pmcsSbsFaultsTable
}

// AS creates new PmcsSbsFaultsTable with assigned alias
func (a PmcsSbsFaultsTable) AS(alias string) *PmcsSbsFaultsTable {
	return newPmcsSbsFaultsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new PmcsSbsFaultsTable with assigned schema name
func (a PmcsSbsFaultsTable) FromSchema(schemaName string) *PmcsSbsFaultsTable {
	return newPmcsSbsFaultsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new PmcsSbsFaultsTable with assigned table prefix
func (a PmcsSbsFaultsTable) WithPrefix(prefix string) *PmcsSbsFaultsTable {
	return newPmcsSbsFaultsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new PmcsSbsFaultsTable with assigned table suffix
func (a PmcsSbsFaultsTable) WithSuffix(suffix string) *PmcsSbsFaultsTable {
	return newPmcsSbsFaultsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newPmcsSbsFaultsTable(schemaName, tableName, alias string) *PmcsSbsFaultsTable {
	return &PmcsSbsFaultsTable{
		pmcsSbsFaultsTable: newPmcsSbsFaultsTableImpl(schemaName, tableName, alias),
		EXCLUDED:           newPmcsSbsFaultsTableImpl("", "excluded", ""),
	}
}

func newPmcsSbsFaultsTableImpl(schemaName, tableName, alias string) pmcsSbsFaultsTable {
	var (
		PmcsIDColumn           = postgres.StringColumn("pmcs_id")
		SectionIDColumn        = postgres.StringColumn("section_id")
		ItemIndexColumn        = postgres.IntegerColumn("item_index")
		ItemNoColumn           = postgres.StringColumn("item_no")
		StatusColumn           = postgres.StringColumn("status")
		FaultTextColumn        = postgres.StringColumn("fault_text")
		CorrectiveActionColumn = postgres.StringColumn("corrective_action")
		CreatedAtColumn        = postgres.TimestampzColumn("created_at")
		UpdatedAtColumn        = postgres.TimestampzColumn("updated_at")
		SectionTitleColumn     = postgres.StringColumn("section_title")
		allColumns             = postgres.ColumnList{PmcsIDColumn, SectionIDColumn, ItemIndexColumn, ItemNoColumn, StatusColumn, FaultTextColumn, CorrectiveActionColumn, CreatedAtColumn, UpdatedAtColumn, SectionTitleColumn}
		mutableColumns         = postgres.ColumnList{ItemNoColumn, StatusColumn, FaultTextColumn, CorrectiveActionColumn, CreatedAtColumn, UpdatedAtColumn, SectionTitleColumn}
		defaultColumns         = postgres.ColumnList{CorrectiveActionColumn, CreatedAtColumn, UpdatedAtColumn}
	)

	return pmcsSbsFaultsTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		PmcsID:           PmcsIDColumn,
		SectionID:        SectionIDColumn,
		ItemIndex:        ItemIndexColumn,
		ItemNo:           ItemNoColumn,
		Status:           StatusColumn,
		FaultText:        FaultTextColumn,
		CorrectiveAction: CorrectiveActionColumn,
		CreatedAt:        CreatedAtColumn,
		UpdatedAt:        UpdatedAtColumn,
		SectionTitle:     SectionTitleColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
