//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var UserPmcsProcedureSteps = newUserPmcsProcedureStepsTable("public", "user_pmcs_procedure_steps", "")

type userPmcsProcedureStepsTable struct {
	postgres.Table

	// Columns
	ID           postgres.ColumnString
	ItemID       postgres.ColumnString
	Position     postgres.ColumnInteger
	StepText     postgres.ColumnString
	FaultFoundIf postgres.ColumnString

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type UserPmcsProcedureStepsTable struct {
	userPmcsProcedureStepsTable

	EXCLUDED userPmcsProcedureStepsTable
}

// AS creates new UserPmcsProcedureStepsTable with assigned alias
func (a UserPmcsProcedureStepsTable) AS(alias string) *UserPmcsProcedureStepsTable {
	return newUserPmcsProcedureStepsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new UserPmcsProcedureStepsTable with assigned schema name
func (a UserPmcsProcedureStepsTable) FromSchema(schemaName string) *UserPmcsProcedureStepsTable {
	return newUserPmcsProcedureStepsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new UserPmcsProcedureStepsTable with assigned table prefix
func (a UserPmcsProcedureStepsTable) WithPrefix(prefix string) *UserPmcsProcedureStepsTable {
	return newUserPmcsProcedureStepsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new UserPmcsProcedureStepsTable with assigned table suffix
func (a UserPmcsProcedureStepsTable) WithSuffix(suffix string) *UserPmcsProcedureStepsTable {
	return newUserPmcsProcedureStepsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newUserPmcsProcedureStepsTable(schemaName, tableName, alias string) *UserPmcsProcedureStepsTable {
	return &UserPmcsProcedureStepsTable{
		userPmcsProcedureStepsTable: newUserPmcsProcedureStepsTableImpl(schemaName, tableName, alias),
		EXCLUDED:                    newUserPmcsProcedureStepsTableImpl("", "excluded", ""),
	}
}

func newUserPmcsProcedureStepsTableImpl(schemaName, tableName, alias string) userPmcsProcedureStepsTable {
	var (
		IDColumn           = postgres.StringColumn("id")
		ItemIDColumn       = postgres.StringColumn("item_id")
		PositionColumn     = postgres.IntegerColumn("position")
		StepTextColumn     = postgres.StringColumn("step_text")
		FaultFoundIfColumn = postgres.StringColumn("fault_found_if")
		allColumns         = postgres.ColumnList{IDColumn, ItemIDColumn, PositionColumn, StepTextColumn, FaultFoundIfColumn}
		mutableColumns     = postgres.ColumnList{ItemIDColumn, PositionColumn, StepTextColumn, FaultFoundIfColumn}
		defaultColumns     = postgres.ColumnList{StepTextColumn, FaultFoundIfColumn}
	)

	return userPmcsProcedureStepsTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:           IDColumn,
		ItemID:       ItemIDColumn,
		Position:     PositionColumn,
		StepText:     StepTextColumn,
		FaultFoundIf: FaultFoundIfColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
