//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var UserPmcsRevisionModels = newUserPmcsRevisionModelsTable("public", "user_pmcs_revision_models", "")

type userPmcsRevisionModelsTable struct {
	postgres.Table

	// Columns
	RevisionID     postgres.ColumnString
	DisplayText    postgres.ColumnString
	NormalizedText postgres.ColumnString

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type UserPmcsRevisionModelsTable struct {
	userPmcsRevisionModelsTable

	EXCLUDED userPmcsRevisionModelsTable
}

// AS creates new UserPmcsRevisionModelsTable with assigned alias
func (a UserPmcsRevisionModelsTable) AS(alias string) *UserPmcsRevisionModelsTable {
	return newUserPmcsRevisionModelsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new UserPmcsRevisionModelsTable with assigned schema name
func (a UserPmcsRevisionModelsTable) FromSchema(schemaName string) *UserPmcsRevisionModelsTable {
	return newUserPmcsRevisionModelsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new UserPmcsRevisionModelsTable with assigned table prefix
func (a UserPmcsRevisionModelsTable) WithPrefix(prefix string) *UserPmcsRevisionModelsTable {
	return newUserPmcsRevisionModelsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new UserPmcsRevisionModelsTable with assigned table suffix
func (a UserPmcsRevisionModelsTable) WithSuffix(suffix string) *UserPmcsRevisionModelsTable {
	return newUserPmcsRevisionModelsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newUserPmcsRevisionModelsTable(schemaName, tableName, alias string) *UserPmcsRevisionModelsTable {
	return &UserPmcsRevisionModelsTable{
		userPmcsRevisionModelsTable: newUserPmcsRevisionModelsTableImpl(schemaName, tableName, alias),
		EXCLUDED:                    newUserPmcsRevisionModelsTableImpl("", "excluded", ""),
	}
}

func newUserPmcsRevisionModelsTableImpl(schemaName, tableName, alias string) userPmcsRevisionModelsTable {
	var (
		RevisionIDColumn     = postgres.StringColumn("revision_id")
		DisplayTextColumn    = postgres.StringColumn("display_text")
		NormalizedTextColumn = postgres.StringColumn("normalized_text")
		allColumns           = postgres.ColumnList{RevisionIDColumn, DisplayTextColumn, NormalizedTextColumn}
		mutableColumns       = postgres.ColumnList{DisplayTextColumn}
		defaultColumns       = postgres.ColumnList{}
	)

	return userPmcsRevisionModelsTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		RevisionID:     RevisionIDColumn,
		DisplayText:    DisplayTextColumn,
		NormalizedText: NormalizedTextColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
