//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var UserPmcsFaults = newUserPmcsFaultsTable("public", "user_pmcs_faults", "")

type userPmcsFaultsTable struct {
	postgres.Table

	// Columns
	PmcsID           postgres.ColumnString
	SectionID        postgres.ColumnString
	ItemIndex        postgres.ColumnInteger
	ItemNo           postgres.ColumnString
	Status           postgres.ColumnString
	FaultText        postgres.ColumnString
	CorrectiveAction postgres.ColumnString
	CreatedAt        postgres.ColumnTimestampz
	UpdatedAt        postgres.ColumnTimestampz
	SectionTitle     postgres.ColumnString

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type UserPmcsFaultsTable struct {
	userPmcsFaultsTable

	EXCLUDED userPmcsFaultsTable
}

// AS creates new UserPmcsFaultsTable with assigned alias
func (a UserPmcsFaultsTable) AS(alias string) *UserPmcsFaultsTable {
	return newUserPmcsFaultsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new UserPmcsFaultsTable with assigned schema name
func (a UserPmcsFaultsTable) FromSchema(schemaName string) *UserPmcsFaultsTable {
	return newUserPmcsFaultsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new UserPmcsFaultsTable with assigned table prefix
func (a UserPmcsFaultsTable) WithPrefix(prefix string) *UserPmcsFaultsTable {
	return newUserPmcsFaultsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new UserPmcsFaultsTable with assigned table suffix
func (a UserPmcsFaultsTable) WithSuffix(suffix string) *UserPmcsFaultsTable {
	return newUserPmcsFaultsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newUserPmcsFaultsTable(schemaName, tableName, alias string) *UserPmcsFaultsTable {
	return &UserPmcsFaultsTable{
		userPmcsFaultsTable: newUserPmcsFaultsTableImpl(schemaName, tableName, alias),
		EXCLUDED:            newUserPmcsFaultsTableImpl("", "excluded", ""),
	}
}

func newUserPmcsFaultsTableImpl(schemaName, tableName, alias string) userPmcsFaultsTable {
	var (
		PmcsIDColumn           = postgres.StringColumn("pmcs_id")
		SectionIDColumn        = postgres.StringColumn("section_id")
		ItemIndexColumn        = postgres.IntegerColumn("item_index")
		ItemNoColumn           = postgres.StringColumn("item_no")
		StatusColumn           = postgres.StringColumn("status")
		FaultTextColumn        = postgres.StringColumn("fault_text")
		CorrectiveActionColumn = postgres.StringColumn("corrective_action")
		CreatedAtColumn        = postgres.TimestampzColumn("created_at")
		UpdatedAtColumn        = postgres.TimestampzColumn("updated_at")
		SectionTitleColumn     = postgres.StringColumn("section_title")
		allColumns             = postgres.ColumnList{PmcsIDColumn, SectionIDColumn, ItemIndexColumn, ItemNoColumn, StatusColumn, FaultTextColumn, CorrectiveActionColumn, CreatedAtColumn, UpdatedAtColumn, SectionTitleColumn}
		mutableColumns         = postgres.ColumnList{ItemNoColumn, StatusColumn, FaultTextColumn, CorrectiveActionColumn, CreatedAtColumn, UpdatedAtColumn, SectionTitleColumn}
		defaultColumns         = postgres.ColumnList{CorrectiveActionColumn, CreatedAtColumn, UpdatedAtColumn}
	)

	return userPmcsFaultsTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		PmcsID:           PmcsIDColumn,
		SectionID:        SectionIDColumn,
		ItemIndex:        ItemIndexColumn,
		ItemNo:           ItemNoColumn,
		Status:           StatusColumn,
		FaultText:        FaultTextColumn,
		CorrectiveAction: CorrectiveActionColumn,
		CreatedAt:        CreatedAtColumn,
		UpdatedAt:        UpdatedAtColumn,
		SectionTitle:     SectionTitleColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
