//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var UserPmcsInspections = newUserPmcsInspectionsTable("public", "user_pmcs_inspections", "")

type userPmcsInspectionsTable struct {
	postgres.Table

	// Columns
	ID                   postgres.ColumnString
	EquipmentID          postgres.ColumnString
	GuideManual          postgres.ColumnString
	PerformedDate        postgres.ColumnTimestampz
	PerformedBy          postgres.ColumnString
	CreatedAt            postgres.ColumnTimestampz
	UpdatedAt            postgres.ColumnTimestampz
	Notes                postgres.ColumnString
	SourceType           postgres.ColumnString
	CustomChecklistID    postgres.ColumnString
	CustomRevisionID     postgres.ColumnString
	CustomRevisionNumber postgres.ColumnInteger
	CustomChecklistName  postgres.ColumnString

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type UserPmcsInspectionsTable struct {
	userPmcsInspectionsTable

	EXCLUDED userPmcsInspectionsTable
}

// AS creates new UserPmcsInspectionsTable with assigned alias
func (a UserPmcsInspectionsTable) AS(alias string) *UserPmcsInspectionsTable {
	return newUserPmcsInspectionsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new UserPmcsInspectionsTable with assigned schema name
func (a UserPmcsInspectionsTable) FromSchema(schemaName string) *UserPmcsInspectionsTable {
	return newUserPmcsInspectionsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new UserPmcsInspectionsTable with assigned table prefix
func (a UserPmcsInspectionsTable) WithPrefix(prefix string) *UserPmcsInspectionsTable {
	return newUserPmcsInspectionsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new UserPmcsInspectionsTable with assigned table suffix
func (a UserPmcsInspectionsTable) WithSuffix(suffix string) *UserPmcsInspectionsTable {
	return newUserPmcsInspectionsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newUserPmcsInspectionsTable(schemaName, tableName, alias string) *UserPmcsInspectionsTable {
	return &UserPmcsInspectionsTable{
		userPmcsInspectionsTable: newUserPmcsInspectionsTableImpl(schemaName, tableName, alias),
		EXCLUDED:                 newUserPmcsInspectionsTableImpl("", "excluded", ""),
	}
}

func newUserPmcsInspectionsTableImpl(schemaName, tableName, alias string) userPmcsInspectionsTable {
	var (
		IDColumn                   = postgres.StringColumn("id")
		EquipmentIDColumn          = postgres.StringColumn("equipment_id")
		GuideManualColumn          = postgres.StringColumn("guide_manual")
		PerformedDateColumn        = postgres.TimestampzColumn("performed_date")
		PerformedByColumn          = postgres.StringColumn("performed_by")
		CreatedAtColumn            = postgres.TimestampzColumn("created_at")
		UpdatedAtColumn            = postgres.TimestampzColumn("updated_at")
		NotesColumn                = postgres.StringColumn("notes")
		SourceTypeColumn           = postgres.StringColumn("source_type")
		CustomChecklistIDColumn    = postgres.StringColumn("custom_checklist_id")
		CustomRevisionIDColumn     = postgres.StringColumn("custom_revision_id")
		CustomRevisionNumberColumn = postgres.IntegerColumn("custom_revision_number")
		CustomChecklistNameColumn  = postgres.StringColumn("custom_checklist_name")
		allColumns                 = postgres.ColumnList{IDColumn, EquipmentIDColumn, GuideManualColumn, PerformedDateColumn, PerformedByColumn, CreatedAtColumn, UpdatedAtColumn, NotesColumn, SourceTypeColumn, CustomChecklistIDColumn, CustomRevisionIDColumn, CustomRevisionNumberColumn, CustomChecklistNameColumn}
		mutableColumns             = postgres.ColumnList{EquipmentIDColumn, GuideManualColumn, PerformedDateColumn, PerformedByColumn, CreatedAtColumn, UpdatedAtColumn, NotesColumn, SourceTypeColumn, CustomChecklistIDColumn, CustomRevisionIDColumn, CustomRevisionNumberColumn, CustomChecklistNameColumn}
		defaultColumns             = postgres.ColumnList{CreatedAtColumn, UpdatedAtColumn}
	)

	return userPmcsInspectionsTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:                   IDColumn,
		EquipmentID:          EquipmentIDColumn,
		GuideManual:          GuideManualColumn,
		PerformedDate:        PerformedDateColumn,
		PerformedBy:          PerformedByColumn,
		CreatedAt:            CreatedAtColumn,
		UpdatedAt:            UpdatedAtColumn,
		Notes:                NotesColumn,
		SourceType:           SourceTypeColumn,
		CustomChecklistID:    CustomChecklistIDColumn,
		CustomRevisionID:     CustomRevisionIDColumn,
		CustomRevisionNumber: CustomRevisionNumberColumn,
		CustomChecklistName:  CustomChecklistNameColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
