//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var UserPmcsSections = newUserPmcsSectionsTable("public", "user_pmcs_sections", "")

type userPmcsSectionsTable struct {
	postgres.Table

	// Columns
	ID         postgres.ColumnString
	RevisionID postgres.ColumnString
	Position   postgres.ColumnInteger
	Title      postgres.ColumnString

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type UserPmcsSectionsTable struct {
	userPmcsSectionsTable

	EXCLUDED userPmcsSectionsTable
}

// AS creates new UserPmcsSectionsTable with assigned alias
func (a UserPmcsSectionsTable) AS(alias string) *UserPmcsSectionsTable {
	return newUserPmcsSectionsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new UserPmcsSectionsTable with assigned schema name
func (a UserPmcsSectionsTable) FromSchema(schemaName string) *UserPmcsSectionsTable {
	return newUserPmcsSectionsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new UserPmcsSectionsTable with assigned table prefix
func (a UserPmcsSectionsTable) WithPrefix(prefix string) *UserPmcsSectionsTable {
	return newUserPmcsSectionsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new UserPmcsSectionsTable with assigned table suffix
func (a UserPmcsSectionsTable) WithSuffix(suffix string) *UserPmcsSectionsTable {
	return newUserPmcsSectionsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newUserPmcsSectionsTable(schemaName, tableName, alias string) *UserPmcsSectionsTable {
	return &UserPmcsSectionsTable{
		userPmcsSectionsTable: newUserPmcsSectionsTableImpl(schemaName, tableName, alias),
		EXCLUDED:              newUserPmcsSectionsTableImpl("", "excluded", ""),
	}
}

func newUserPmcsSectionsTableImpl(schemaName, tableName, alias string) userPmcsSectionsTable {
	var (
		IDColumn         = postgres.StringColumn("id")
		RevisionIDColumn = postgres.StringColumn("revision_id")
		PositionColumn   = postgres.IntegerColumn("position")
		TitleColumn      = postgres.StringColumn("title")
		allColumns       = postgres.ColumnList{IDColumn, RevisionIDColumn, PositionColumn, TitleColumn}
		mutableColumns   = postgres.ColumnList{RevisionIDColumn, PositionColumn, TitleColumn}
		defaultColumns   = postgres.ColumnList{TitleColumn}
	)

	return userPmcsSectionsTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:         IDColumn,
		RevisionID: RevisionIDColumn,
		Position:   PositionColumn,
		Title:      TitleColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
