//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var UserPmcsContentUUIDReservations = newUserPmcsContentUUIDReservationsTable("public", "user_pmcs_content_uuid_reservations", "")

type userPmcsContentUUIDReservationsTable struct {
	postgres.Table

	// Columns
	ID postgres.ColumnString

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type UserPmcsContentUUIDReservationsTable struct {
	userPmcsContentUUIDReservationsTable

	EXCLUDED userPmcsContentUUIDReservationsTable
}

// AS creates new UserPmcsContentUUIDReservationsTable with assigned alias
func (a UserPmcsContentUUIDReservationsTable) AS(alias string) *UserPmcsContentUUIDReservationsTable {
	return newUserPmcsContentUUIDReservationsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new UserPmcsContentUUIDReservationsTable with assigned schema name
func (a UserPmcsContentUUIDReservationsTable) FromSchema(schemaName string) *UserPmcsContentUUIDReservationsTable {
	return newUserPmcsContentUUIDReservationsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new UserPmcsContentUUIDReservationsTable with assigned table prefix
func (a UserPmcsContentUUIDReservationsTable) WithPrefix(prefix string) *UserPmcsContentUUIDReservationsTable {
	return newUserPmcsContentUUIDReservationsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new UserPmcsContentUUIDReservationsTable with assigned table suffix
func (a UserPmcsContentUUIDReservationsTable) WithSuffix(suffix string) *UserPmcsContentUUIDReservationsTable {
	return newUserPmcsContentUUIDReservationsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newUserPmcsContentUUIDReservationsTable(schemaName, tableName, alias string) *UserPmcsContentUUIDReservationsTable {
	return &UserPmcsContentUUIDReservationsTable{
		userPmcsContentUUIDReservationsTable: newUserPmcsContentUUIDReservationsTableImpl(schemaName, tableName, alias),
		EXCLUDED:                             newUserPmcsContentUUIDReservationsTableImpl("", "excluded", ""),
	}
}

func newUserPmcsContentUUIDReservationsTableImpl(schemaName, tableName, alias string) userPmcsContentUUIDReservationsTable {
	var (
		IDColumn       = postgres.StringColumn("id")
		allColumns     = postgres.ColumnList{IDColumn}
		mutableColumns = postgres.ColumnList{}
		defaultColumns = postgres.ColumnList{}
	)

	return userPmcsContentUUIDReservationsTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID: IDColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
