//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var UserPmcsNotices = newUserPmcsNoticesTable("public", "user_pmcs_notices", "")

type userPmcsNoticesTable struct {
	postgres.Table

	// Columns
	ID         postgres.ColumnString
	ItemID     postgres.ColumnString
	Position   postgres.ColumnInteger
	Type       postgres.ColumnString
	NoticeText postgres.ColumnString

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type UserPmcsNoticesTable struct {
	userPmcsNoticesTable

	EXCLUDED userPmcsNoticesTable
}

// AS creates new UserPmcsNoticesTable with assigned alias
func (a UserPmcsNoticesTable) AS(alias string) *UserPmcsNoticesTable {
	return newUserPmcsNoticesTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new UserPmcsNoticesTable with assigned schema name
func (a UserPmcsNoticesTable) FromSchema(schemaName string) *UserPmcsNoticesTable {
	return newUserPmcsNoticesTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new UserPmcsNoticesTable with assigned table prefix
func (a UserPmcsNoticesTable) WithPrefix(prefix string) *UserPmcsNoticesTable {
	return newUserPmcsNoticesTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new UserPmcsNoticesTable with assigned table suffix
func (a UserPmcsNoticesTable) WithSuffix(suffix string) *UserPmcsNoticesTable {
	return newUserPmcsNoticesTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newUserPmcsNoticesTable(schemaName, tableName, alias string) *UserPmcsNoticesTable {
	return &UserPmcsNoticesTable{
		userPmcsNoticesTable: newUserPmcsNoticesTableImpl(schemaName, tableName, alias),
		EXCLUDED:             newUserPmcsNoticesTableImpl("", "excluded", ""),
	}
}

func newUserPmcsNoticesTableImpl(schemaName, tableName, alias string) userPmcsNoticesTable {
	var (
		IDColumn         = postgres.StringColumn("id")
		ItemIDColumn     = postgres.StringColumn("item_id")
		PositionColumn   = postgres.IntegerColumn("position")
		TypeColumn       = postgres.StringColumn("type")
		NoticeTextColumn = postgres.StringColumn("notice_text")
		allColumns       = postgres.ColumnList{IDColumn, ItemIDColumn, PositionColumn, TypeColumn, NoticeTextColumn}
		mutableColumns   = postgres.ColumnList{ItemIDColumn, PositionColumn, TypeColumn, NoticeTextColumn}
		defaultColumns   = postgres.ColumnList{NoticeTextColumn}
	)

	return userPmcsNoticesTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:         IDColumn,
		ItemID:     ItemIDColumn,
		Position:   PositionColumn,
		Type:       TypeColumn,
		NoticeText: NoticeTextColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
