//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var UserPmcsCommunitySources = newUserPmcsCommunitySourcesTable("public", "user_pmcs_community_sources", "")

type userPmcsCommunitySourcesTable struct {
	postgres.Table

	// Columns
	ChecklistID                 postgres.ColumnString
	Status                      postgres.ColumnString
	CurrentReleaseRevisionID    postgres.ColumnString
	LatestReleaseRevisionNumber postgres.ColumnInteger
	FirstReleasedAt             postgres.ColumnTimestampz
	UpdatedAt                   postgres.ColumnTimestampz
	RetiredAt                   postgres.ColumnTimestampz

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type UserPmcsCommunitySourcesTable struct {
	userPmcsCommunitySourcesTable

	EXCLUDED userPmcsCommunitySourcesTable
}

// AS creates new UserPmcsCommunitySourcesTable with assigned alias
func (a UserPmcsCommunitySourcesTable) AS(alias string) *UserPmcsCommunitySourcesTable {
	return newUserPmcsCommunitySourcesTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new UserPmcsCommunitySourcesTable with assigned schema name
func (a UserPmcsCommunitySourcesTable) FromSchema(schemaName string) *UserPmcsCommunitySourcesTable {
	return newUserPmcsCommunitySourcesTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new UserPmcsCommunitySourcesTable with assigned table prefix
func (a UserPmcsCommunitySourcesTable) WithPrefix(prefix string) *UserPmcsCommunitySourcesTable {
	return newUserPmcsCommunitySourcesTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new UserPmcsCommunitySourcesTable with assigned table suffix
func (a UserPmcsCommunitySourcesTable) WithSuffix(suffix string) *UserPmcsCommunitySourcesTable {
	return newUserPmcsCommunitySourcesTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newUserPmcsCommunitySourcesTable(schemaName, tableName, alias string) *UserPmcsCommunitySourcesTable {
	return &UserPmcsCommunitySourcesTable{
		userPmcsCommunitySourcesTable: newUserPmcsCommunitySourcesTableImpl(schemaName, tableName, alias),
		EXCLUDED:                      newUserPmcsCommunitySourcesTableImpl("", "excluded", ""),
	}
}

func newUserPmcsCommunitySourcesTableImpl(schemaName, tableName, alias string) userPmcsCommunitySourcesTable {
	var (
		ChecklistIDColumn                 = postgres.StringColumn("checklist_id")
		StatusColumn                      = postgres.StringColumn("status")
		CurrentReleaseRevisionIDColumn    = postgres.StringColumn("current_release_revision_id")
		LatestReleaseRevisionNumberColumn = postgres.IntegerColumn("latest_release_revision_number")
		FirstReleasedAtColumn             = postgres.TimestampzColumn("first_released_at")
		UpdatedAtColumn                   = postgres.TimestampzColumn("updated_at")
		RetiredAtColumn                   = postgres.TimestampzColumn("retired_at")
		allColumns                        = postgres.ColumnList{ChecklistIDColumn, StatusColumn, CurrentReleaseRevisionIDColumn, LatestReleaseRevisionNumberColumn, FirstReleasedAtColumn, UpdatedAtColumn, RetiredAtColumn}
		mutableColumns                    = postgres.ColumnList{StatusColumn, CurrentReleaseRevisionIDColumn, LatestReleaseRevisionNumberColumn, FirstReleasedAtColumn, UpdatedAtColumn, RetiredAtColumn}
		defaultColumns                    = postgres.ColumnList{}
	)

	return userPmcsCommunitySourcesTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ChecklistID:                 ChecklistIDColumn,
		Status:                      StatusColumn,
		CurrentReleaseRevisionID:    CurrentReleaseRevisionIDColumn,
		LatestReleaseRevisionNumber: LatestReleaseRevisionNumberColumn,
		FirstReleasedAt:             FirstReleasedAtColumn,
		UpdatedAt:                   UpdatedAtColumn,
		RetiredAt:                   RetiredAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
