//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var UserPmcsSyncState = newUserPmcsSyncStateTable("public", "user_pmcs_sync_state", "")

type userPmcsSyncStateTable struct {
	postgres.Table

	// Columns
	UserUID        postgres.ColumnString
	CurrentVersion postgres.ColumnInteger
	UpdatedAt      postgres.ColumnTimestampz

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type UserPmcsSyncStateTable struct {
	userPmcsSyncStateTable

	EXCLUDED userPmcsSyncStateTable
}

// AS creates new UserPmcsSyncStateTable with assigned alias
func (a UserPmcsSyncStateTable) AS(alias string) *UserPmcsSyncStateTable {
	return newUserPmcsSyncStateTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new UserPmcsSyncStateTable with assigned schema name
func (a UserPmcsSyncStateTable) FromSchema(schemaName string) *UserPmcsSyncStateTable {
	return newUserPmcsSyncStateTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new UserPmcsSyncStateTable with assigned table prefix
func (a UserPmcsSyncStateTable) WithPrefix(prefix string) *UserPmcsSyncStateTable {
	return newUserPmcsSyncStateTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new UserPmcsSyncStateTable with assigned table suffix
func (a UserPmcsSyncStateTable) WithSuffix(suffix string) *UserPmcsSyncStateTable {
	return newUserPmcsSyncStateTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newUserPmcsSyncStateTable(schemaName, tableName, alias string) *UserPmcsSyncStateTable {
	return &UserPmcsSyncStateTable{
		userPmcsSyncStateTable: newUserPmcsSyncStateTableImpl(schemaName, tableName, alias),
		EXCLUDED:               newUserPmcsSyncStateTableImpl("", "excluded", ""),
	}
}

func newUserPmcsSyncStateTableImpl(schemaName, tableName, alias string) userPmcsSyncStateTable {
	var (
		UserUIDColumn        = postgres.StringColumn("user_uid")
		CurrentVersionColumn = postgres.IntegerColumn("current_version")
		UpdatedAtColumn      = postgres.TimestampzColumn("updated_at")
		allColumns           = postgres.ColumnList{UserUIDColumn, CurrentVersionColumn, UpdatedAtColumn}
		mutableColumns       = postgres.ColumnList{CurrentVersionColumn, UpdatedAtColumn}
		defaultColumns       = postgres.ColumnList{CurrentVersionColumn, UpdatedAtColumn}
	)

	return userPmcsSyncStateTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		UserUID:        UserUIDColumn,
		CurrentVersion: CurrentVersionColumn,
		UpdatedAt:      UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
