//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var UserPmcsCommunityVotes = newUserPmcsCommunityVotesTable("public", "user_pmcs_community_votes", "")

type userPmcsCommunityVotesTable struct {
	postgres.Table

	// Columns
	ChecklistID postgres.ColumnString
	VoterUID    postgres.ColumnString
	Direction   postgres.ColumnInteger
	CreatedAt   postgres.ColumnTimestampz
	UpdatedAt   postgres.ColumnTimestampz

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type UserPmcsCommunityVotesTable struct {
	userPmcsCommunityVotesTable

	EXCLUDED userPmcsCommunityVotesTable
}

// AS creates new UserPmcsCommunityVotesTable with assigned alias
func (a UserPmcsCommunityVotesTable) AS(alias string) *UserPmcsCommunityVotesTable {
	return newUserPmcsCommunityVotesTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new UserPmcsCommunityVotesTable with assigned schema name
func (a UserPmcsCommunityVotesTable) FromSchema(schemaName string) *UserPmcsCommunityVotesTable {
	return newUserPmcsCommunityVotesTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new UserPmcsCommunityVotesTable with assigned table prefix
func (a UserPmcsCommunityVotesTable) WithPrefix(prefix string) *UserPmcsCommunityVotesTable {
	return newUserPmcsCommunityVotesTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new UserPmcsCommunityVotesTable with assigned table suffix
func (a UserPmcsCommunityVotesTable) WithSuffix(suffix string) *UserPmcsCommunityVotesTable {
	return newUserPmcsCommunityVotesTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newUserPmcsCommunityVotesTable(schemaName, tableName, alias string) *UserPmcsCommunityVotesTable {
	return &UserPmcsCommunityVotesTable{
		userPmcsCommunityVotesTable: newUserPmcsCommunityVotesTableImpl(schemaName, tableName, alias),
		EXCLUDED:                    newUserPmcsCommunityVotesTableImpl("", "excluded", ""),
	}
}

func newUserPmcsCommunityVotesTableImpl(schemaName, tableName, alias string) userPmcsCommunityVotesTable {
	var (
		ChecklistIDColumn = postgres.StringColumn("checklist_id")
		VoterUIDColumn    = postgres.StringColumn("voter_uid")
		DirectionColumn   = postgres.IntegerColumn("direction")
		CreatedAtColumn   = postgres.TimestampzColumn("created_at")
		UpdatedAtColumn   = postgres.TimestampzColumn("updated_at")
		allColumns        = postgres.ColumnList{ChecklistIDColumn, VoterUIDColumn, DirectionColumn, CreatedAtColumn, UpdatedAtColumn}
		mutableColumns    = postgres.ColumnList{DirectionColumn, CreatedAtColumn, UpdatedAtColumn}
		defaultColumns    = postgres.ColumnList{CreatedAtColumn, UpdatedAtColumn}
	)

	return userPmcsCommunityVotesTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ChecklistID: ChecklistIDColumn,
		VoterUID:    VoterUIDColumn,
		Direction:   DirectionColumn,
		CreatedAt:   CreatedAtColumn,
		UpdatedAt:   UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
