//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var UserPmcsItems = newUserPmcsItemsTable("public", "user_pmcs_items", "")

type userPmcsItemsTable struct {
	postgres.Table

	// Columns
	ID                        postgres.ColumnString
	SectionID                 postgres.ColumnString
	Position                  postgres.ColumnInteger
	Interval                  postgres.ColumnString
	ItemToBeCheckedOrServiced postgres.ColumnString
	PerformedBy               postgres.ColumnString

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type UserPmcsItemsTable struct {
	userPmcsItemsTable

	EXCLUDED userPmcsItemsTable
}

// AS creates new UserPmcsItemsTable with assigned alias
func (a UserPmcsItemsTable) AS(alias string) *UserPmcsItemsTable {
	return newUserPmcsItemsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new UserPmcsItemsTable with assigned schema name
func (a UserPmcsItemsTable) FromSchema(schemaName string) *UserPmcsItemsTable {
	return newUserPmcsItemsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new UserPmcsItemsTable with assigned table prefix
func (a UserPmcsItemsTable) WithPrefix(prefix string) *UserPmcsItemsTable {
	return newUserPmcsItemsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new UserPmcsItemsTable with assigned table suffix
func (a UserPmcsItemsTable) WithSuffix(suffix string) *UserPmcsItemsTable {
	return newUserPmcsItemsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newUserPmcsItemsTable(schemaName, tableName, alias string) *UserPmcsItemsTable {
	return &UserPmcsItemsTable{
		userPmcsItemsTable: newUserPmcsItemsTableImpl(schemaName, tableName, alias),
		EXCLUDED:           newUserPmcsItemsTableImpl("", "excluded", ""),
	}
}

func newUserPmcsItemsTableImpl(schemaName, tableName, alias string) userPmcsItemsTable {
	var (
		IDColumn                        = postgres.StringColumn("id")
		SectionIDColumn                 = postgres.StringColumn("section_id")
		PositionColumn                  = postgres.IntegerColumn("position")
		IntervalColumn                  = postgres.StringColumn("interval")
		ItemToBeCheckedOrServicedColumn = postgres.StringColumn("item_to_be_checked_or_serviced")
		PerformedByColumn               = postgres.StringColumn("performed_by")
		allColumns                      = postgres.ColumnList{IDColumn, SectionIDColumn, PositionColumn, IntervalColumn, ItemToBeCheckedOrServicedColumn, PerformedByColumn}
		mutableColumns                  = postgres.ColumnList{SectionIDColumn, PositionColumn, IntervalColumn, ItemToBeCheckedOrServicedColumn, PerformedByColumn}
		defaultColumns                  = postgres.ColumnList{IntervalColumn, ItemToBeCheckedOrServicedColumn, PerformedByColumn}
	)

	return userPmcsItemsTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:                        IDColumn,
		SectionID:                 SectionIDColumn,
		Position:                  PositionColumn,
		Interval:                  IntervalColumn,
		ItemToBeCheckedOrServiced: ItemToBeCheckedOrServicedColumn,
		PerformedBy:               PerformedByColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
