//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var UserPmcsChecklists = newUserPmcsChecklistsTable("public", "user_pmcs_checklists", "")

type userPmcsChecklistsTable struct {
	postgres.Table

	// Columns
	ID                   postgres.ColumnString
	OwnerUID             postgres.ColumnString
	SyncVersion          postgres.ColumnInteger
	AccountChangeVersion postgres.ColumnInteger
	CreatedAt            postgres.ColumnTimestampz
	UpdatedAt            postgres.ColumnTimestampz
	DeletedAt            postgres.ColumnTimestampz

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type UserPmcsChecklistsTable struct {
	userPmcsChecklistsTable

	EXCLUDED userPmcsChecklistsTable
}

// AS creates new UserPmcsChecklistsTable with assigned alias
func (a UserPmcsChecklistsTable) AS(alias string) *UserPmcsChecklistsTable {
	return newUserPmcsChecklistsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new UserPmcsChecklistsTable with assigned schema name
func (a UserPmcsChecklistsTable) FromSchema(schemaName string) *UserPmcsChecklistsTable {
	return newUserPmcsChecklistsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new UserPmcsChecklistsTable with assigned table prefix
func (a UserPmcsChecklistsTable) WithPrefix(prefix string) *UserPmcsChecklistsTable {
	return newUserPmcsChecklistsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new UserPmcsChecklistsTable with assigned table suffix
func (a UserPmcsChecklistsTable) WithSuffix(suffix string) *UserPmcsChecklistsTable {
	return newUserPmcsChecklistsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newUserPmcsChecklistsTable(schemaName, tableName, alias string) *UserPmcsChecklistsTable {
	return &UserPmcsChecklistsTable{
		userPmcsChecklistsTable: newUserPmcsChecklistsTableImpl(schemaName, tableName, alias),
		EXCLUDED:                newUserPmcsChecklistsTableImpl("", "excluded", ""),
	}
}

func newUserPmcsChecklistsTableImpl(schemaName, tableName, alias string) userPmcsChecklistsTable {
	var (
		IDColumn                   = postgres.StringColumn("id")
		OwnerUIDColumn             = postgres.StringColumn("owner_uid")
		SyncVersionColumn          = postgres.IntegerColumn("sync_version")
		AccountChangeVersionColumn = postgres.IntegerColumn("account_change_version")
		CreatedAtColumn            = postgres.TimestampzColumn("created_at")
		UpdatedAtColumn            = postgres.TimestampzColumn("updated_at")
		DeletedAtColumn            = postgres.TimestampzColumn("deleted_at")
		allColumns                 = postgres.ColumnList{IDColumn, OwnerUIDColumn, SyncVersionColumn, AccountChangeVersionColumn, CreatedAtColumn, UpdatedAtColumn, DeletedAtColumn}
		mutableColumns             = postgres.ColumnList{OwnerUIDColumn, SyncVersionColumn, AccountChangeVersionColumn, CreatedAtColumn, UpdatedAtColumn, DeletedAtColumn}
		defaultColumns             = postgres.ColumnList{CreatedAtColumn, UpdatedAtColumn}
	)

	return userPmcsChecklistsTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:                   IDColumn,
		OwnerUID:             OwnerUIDColumn,
		SyncVersion:          SyncVersionColumn,
		AccountChangeVersion: AccountChangeVersionColumn,
		CreatedAt:            CreatedAtColumn,
		UpdatedAt:            UpdatedAtColumn,
		DeletedAt:            DeletedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
