//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var UserPmcsSubscriptions = newUserPmcsSubscriptionsTable("public", "user_pmcs_subscriptions", "")

type userPmcsSubscriptionsTable struct {
	postgres.Table

	// Columns
	SubscriberUID        postgres.ColumnString
	ChecklistID          postgres.ColumnString
	InstalledRevisionID  postgres.ColumnString
	SyncVersion          postgres.ColumnInteger
	AccountChangeVersion postgres.ColumnInteger
	CreatedAt            postgres.ColumnTimestampz
	UpdatedAt            postgres.ColumnTimestampz
	DeletedAt            postgres.ColumnTimestampz

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type UserPmcsSubscriptionsTable struct {
	userPmcsSubscriptionsTable

	EXCLUDED userPmcsSubscriptionsTable
}

// AS creates new UserPmcsSubscriptionsTable with assigned alias
func (a UserPmcsSubscriptionsTable) AS(alias string) *UserPmcsSubscriptionsTable {
	return newUserPmcsSubscriptionsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new UserPmcsSubscriptionsTable with assigned schema name
func (a UserPmcsSubscriptionsTable) FromSchema(schemaName string) *UserPmcsSubscriptionsTable {
	return newUserPmcsSubscriptionsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new UserPmcsSubscriptionsTable with assigned table prefix
func (a UserPmcsSubscriptionsTable) WithPrefix(prefix string) *UserPmcsSubscriptionsTable {
	return newUserPmcsSubscriptionsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new UserPmcsSubscriptionsTable with assigned table suffix
func (a UserPmcsSubscriptionsTable) WithSuffix(suffix string) *UserPmcsSubscriptionsTable {
	return newUserPmcsSubscriptionsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newUserPmcsSubscriptionsTable(schemaName, tableName, alias string) *UserPmcsSubscriptionsTable {
	return &UserPmcsSubscriptionsTable{
		userPmcsSubscriptionsTable: newUserPmcsSubscriptionsTableImpl(schemaName, tableName, alias),
		EXCLUDED:                   newUserPmcsSubscriptionsTableImpl("", "excluded", ""),
	}
}

func newUserPmcsSubscriptionsTableImpl(schemaName, tableName, alias string) userPmcsSubscriptionsTable {
	var (
		SubscriberUIDColumn        = postgres.StringColumn("subscriber_uid")
		ChecklistIDColumn          = postgres.StringColumn("checklist_id")
		InstalledRevisionIDColumn  = postgres.StringColumn("installed_revision_id")
		SyncVersionColumn          = postgres.IntegerColumn("sync_version")
		AccountChangeVersionColumn = postgres.IntegerColumn("account_change_version")
		CreatedAtColumn            = postgres.TimestampzColumn("created_at")
		UpdatedAtColumn            = postgres.TimestampzColumn("updated_at")
		DeletedAtColumn            = postgres.TimestampzColumn("deleted_at")
		allColumns                 = postgres.ColumnList{SubscriberUIDColumn, ChecklistIDColumn, InstalledRevisionIDColumn, SyncVersionColumn, AccountChangeVersionColumn, CreatedAtColumn, UpdatedAtColumn, DeletedAtColumn}
		mutableColumns             = postgres.ColumnList{InstalledRevisionIDColumn, SyncVersionColumn, AccountChangeVersionColumn, CreatedAtColumn, UpdatedAtColumn, DeletedAtColumn}
		defaultColumns             = postgres.ColumnList{CreatedAtColumn, UpdatedAtColumn}
	)

	return userPmcsSubscriptionsTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		SubscriberUID:        SubscriberUIDColumn,
		ChecklistID:          ChecklistIDColumn,
		InstalledRevisionID:  InstalledRevisionIDColumn,
		SyncVersion:          SyncVersionColumn,
		AccountChangeVersion: AccountChangeVersionColumn,
		CreatedAt:            CreatedAtColumn,
		UpdatedAt:            UpdatedAtColumn,
		DeletedAt:            DeletedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
