//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var UserPmcsSectionModels = newUserPmcsSectionModelsTable("public", "user_pmcs_section_models", "")

type userPmcsSectionModelsTable struct {
	postgres.Table

	// Columns
	SectionID      postgres.ColumnString
	DisplayText    postgres.ColumnString
	NormalizedText postgres.ColumnString

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type UserPmcsSectionModelsTable struct {
	userPmcsSectionModelsTable

	EXCLUDED userPmcsSectionModelsTable
}

// AS creates new UserPmcsSectionModelsTable with assigned alias
func (a UserPmcsSectionModelsTable) AS(alias string) *UserPmcsSectionModelsTable {
	return newUserPmcsSectionModelsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new UserPmcsSectionModelsTable with assigned schema name
func (a UserPmcsSectionModelsTable) FromSchema(schemaName string) *UserPmcsSectionModelsTable {
	return newUserPmcsSectionModelsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new UserPmcsSectionModelsTable with assigned table prefix
func (a UserPmcsSectionModelsTable) WithPrefix(prefix string) *UserPmcsSectionModelsTable {
	return newUserPmcsSectionModelsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new UserPmcsSectionModelsTable with assigned table suffix
func (a UserPmcsSectionModelsTable) WithSuffix(suffix string) *UserPmcsSectionModelsTable {
	return newUserPmcsSectionModelsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newUserPmcsSectionModelsTable(schemaName, tableName, alias string) *UserPmcsSectionModelsTable {
	return &UserPmcsSectionModelsTable{
		userPmcsSectionModelsTable: newUserPmcsSectionModelsTableImpl(schemaName, tableName, alias),
		EXCLUDED:                   newUserPmcsSectionModelsTableImpl("", "excluded", ""),
	}
}

func newUserPmcsSectionModelsTableImpl(schemaName, tableName, alias string) userPmcsSectionModelsTable {
	var (
		SectionIDColumn      = postgres.StringColumn("section_id")
		DisplayTextColumn    = postgres.StringColumn("display_text")
		NormalizedTextColumn = postgres.StringColumn("normalized_text")
		allColumns           = postgres.ColumnList{SectionIDColumn, DisplayTextColumn, NormalizedTextColumn}
		mutableColumns       = postgres.ColumnList{DisplayTextColumn}
		defaultColumns       = postgres.ColumnList{}
	)

	return userPmcsSectionModelsTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		SectionID:      SectionIDColumn,
		DisplayText:    DisplayTextColumn,
		NormalizedText: NormalizedTextColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
