//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var UserPmcsRevisions = newUserPmcsRevisionsTable("public", "user_pmcs_revisions", "")

type userPmcsRevisionsTable struct {
	postgres.Table

	// Columns
	ID             postgres.ColumnString
	ChecklistID    postgres.ColumnString
	State          postgres.ColumnString
	RevisionNumber postgres.ColumnInteger
	Name           postgres.ColumnString
	Description    postgres.ColumnString
	ContentHash    postgres.ColumnBytea
	CreatedAt      postgres.ColumnTimestampz
	UpdatedAt      postgres.ColumnTimestampz
	PublishedAt    postgres.ColumnTimestampz

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type UserPmcsRevisionsTable struct {
	userPmcsRevisionsTable

	EXCLUDED userPmcsRevisionsTable
}

// AS creates new UserPmcsRevisionsTable with assigned alias
func (a UserPmcsRevisionsTable) AS(alias string) *UserPmcsRevisionsTable {
	return newUserPmcsRevisionsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new UserPmcsRevisionsTable with assigned schema name
func (a UserPmcsRevisionsTable) FromSchema(schemaName string) *UserPmcsRevisionsTable {
	return newUserPmcsRevisionsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new UserPmcsRevisionsTable with assigned table prefix
func (a UserPmcsRevisionsTable) WithPrefix(prefix string) *UserPmcsRevisionsTable {
	return newUserPmcsRevisionsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new UserPmcsRevisionsTable with assigned table suffix
func (a UserPmcsRevisionsTable) WithSuffix(suffix string) *UserPmcsRevisionsTable {
	return newUserPmcsRevisionsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newUserPmcsRevisionsTable(schemaName, tableName, alias string) *UserPmcsRevisionsTable {
	return &UserPmcsRevisionsTable{
		userPmcsRevisionsTable: newUserPmcsRevisionsTableImpl(schemaName, tableName, alias),
		EXCLUDED:               newUserPmcsRevisionsTableImpl("", "excluded", ""),
	}
}

func newUserPmcsRevisionsTableImpl(schemaName, tableName, alias string) userPmcsRevisionsTable {
	var (
		IDColumn             = postgres.StringColumn("id")
		ChecklistIDColumn    = postgres.StringColumn("checklist_id")
		StateColumn          = postgres.StringColumn("state")
		RevisionNumberColumn = postgres.IntegerColumn("revision_number")
		NameColumn           = postgres.StringColumn("name")
		DescriptionColumn    = postgres.StringColumn("description")
		ContentHashColumn    = postgres.ByteaColumn("content_hash")
		CreatedAtColumn      = postgres.TimestampzColumn("created_at")
		UpdatedAtColumn      = postgres.TimestampzColumn("updated_at")
		PublishedAtColumn    = postgres.TimestampzColumn("published_at")
		allColumns           = postgres.ColumnList{IDColumn, ChecklistIDColumn, StateColumn, RevisionNumberColumn, NameColumn, DescriptionColumn, ContentHashColumn, CreatedAtColumn, UpdatedAtColumn, PublishedAtColumn}
		mutableColumns       = postgres.ColumnList{ChecklistIDColumn, StateColumn, RevisionNumberColumn, NameColumn, DescriptionColumn, ContentHashColumn, CreatedAtColumn, UpdatedAtColumn, PublishedAtColumn}
		defaultColumns       = postgres.ColumnList{NameColumn, DescriptionColumn, CreatedAtColumn, UpdatedAtColumn}
	)

	return userPmcsRevisionsTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:             IDColumn,
		ChecklistID:    ChecklistIDColumn,
		State:          StateColumn,
		RevisionNumber: RevisionNumberColumn,
		Name:           NameColumn,
		Description:    DescriptionColumn,
		ContentHash:    ContentHashColumn,
		CreatedAt:      CreatedAtColumn,
		UpdatedAt:      UpdatedAtColumn,
		PublishedAt:    PublishedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
