//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var UserPmcsCommunityReleases = newUserPmcsCommunityReleasesTable("public", "user_pmcs_community_releases", "")

type userPmcsCommunityReleasesTable struct {
	postgres.Table

	// Columns
	RevisionID  postgres.ColumnString
	ChecklistID postgres.ColumnString
	ReleasedAt  postgres.ColumnTimestampz

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type UserPmcsCommunityReleasesTable struct {
	userPmcsCommunityReleasesTable

	EXCLUDED userPmcsCommunityReleasesTable
}

// AS creates new UserPmcsCommunityReleasesTable with assigned alias
func (a UserPmcsCommunityReleasesTable) AS(alias string) *UserPmcsCommunityReleasesTable {
	return newUserPmcsCommunityReleasesTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new UserPmcsCommunityReleasesTable with assigned schema name
func (a UserPmcsCommunityReleasesTable) FromSchema(schemaName string) *UserPmcsCommunityReleasesTable {
	return newUserPmcsCommunityReleasesTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new UserPmcsCommunityReleasesTable with assigned table prefix
func (a UserPmcsCommunityReleasesTable) WithPrefix(prefix string) *UserPmcsCommunityReleasesTable {
	return newUserPmcsCommunityReleasesTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new UserPmcsCommunityReleasesTable with assigned table suffix
func (a UserPmcsCommunityReleasesTable) WithSuffix(suffix string) *UserPmcsCommunityReleasesTable {
	return newUserPmcsCommunityReleasesTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newUserPmcsCommunityReleasesTable(schemaName, tableName, alias string) *UserPmcsCommunityReleasesTable {
	return &UserPmcsCommunityReleasesTable{
		userPmcsCommunityReleasesTable: newUserPmcsCommunityReleasesTableImpl(schemaName, tableName, alias),
		EXCLUDED:                       newUserPmcsCommunityReleasesTableImpl("", "excluded", ""),
	}
}

func newUserPmcsCommunityReleasesTableImpl(schemaName, tableName, alias string) userPmcsCommunityReleasesTable {
	var (
		RevisionIDColumn  = postgres.StringColumn("revision_id")
		ChecklistIDColumn = postgres.StringColumn("checklist_id")
		ReleasedAtColumn  = postgres.TimestampzColumn("released_at")
		allColumns        = postgres.ColumnList{RevisionIDColumn, ChecklistIDColumn, ReleasedAtColumn}
		mutableColumns    = postgres.ColumnList{ChecklistIDColumn, ReleasedAtColumn}
		defaultColumns    = postgres.ColumnList{ReleasedAtColumn}
	)

	return userPmcsCommunityReleasesTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		RevisionID:  RevisionIDColumn,
		ChecklistID: ChecklistIDColumn,
		ReleasedAt:  ReleasedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
